#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 10

bspc config focused_border_color   "#282828"   # focused window
bspc config normal_border_color   "#1d2021"   # unfocused window
bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
export PATH="/usr/local/bin:$PATH"
mpd &
mpDris2 &
sxhkd &
picom &
polybar &
feh --bg-fill test1.png &
xrandr --output DVI-I-0 --brightness 1.30 --gamma 0.70:0.70:0.70 &
